[font]
size = 12.0

[font.normal]
family = "FiraCode Nerd Font Ret"
style = "Regular"

[shell]
program = "/usr/bin/nu"

[bell]
duration = 1000
animation = "EaseOutSine"

[cursor]
style = { shape = "Underline", blinking = "Always" }
blink_timeout = 0
unfocused_hollow = false

[mouse]
hide_when_typing = true
